name: Create Tag

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: crashteamdev/action-tagger@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          with-v: true
